#!/usr/bin/env python

from distutils.core import setup
setup(name='ISO8583 Module',
		version='1.0',
		description='ISO8583 LIBRARY',
		author='Igor V. Custodio',
		author_email='igorvc@vulcanno.com.br',
		url='http://www.vulcanno.com.br/python',
		packages=['ISO8583'],
		classifiers=[
		'Development Status :: 3 - Beta',
		'Environment :: Console',
		'Intended Audience :: Financial and Insurance Industry',
		'Intended Audience :: Telecommunications Industry',
		'Intended Audience :: Developers',
		'License :: OSI Approved :: GNU General Public License (GPL)',
		'Operating System :: OS Independent',
		'Operating System :: Windows',
		'Operating System :: Linux',
		'Operating System :: Unix',
		'Operating System :: MacOS',
		'Programming Language :: Python',
		'Topic :: Financial',
		'Topic :: Communications',
		'Natural Language :: Arabic',
		'Natural Language :: Bulgarian',
		'Natural Language :: Catalan',
		'Natural Language :: Chinese (Simplified)',
		'Natural Language :: Chinese (Traditional)',
		'Natural Language :: Czech',
		'Natural Language :: Danish',
		'Natural Language :: Dutch',
		'Natural Language :: English',
		'Natural Language :: Esperanto',
		'Natural Language :: Finnish',
		'Natural Language :: French',
		'Natural Language :: German',
		'Natural Language :: Greek',
		'Natural Language :: Hebrew',
		'Natural Language :: Hungarian',
		'Natural Language :: Indonesian',
		'Natural Language :: Italian',
		'Natural Language :: Japanese',
		'Natural Language :: Korean',
		'Natural Language :: Latvian',
		'Natural Language :: Marathi',
		'Natural Language :: Persian',
		'Natural Language :: Polish',
		'Natural Language :: Portuguese',
		'Natural Language :: Portuguese (Brazilian)',
		'Natural Language :: Romanian',
		'Natural Language :: Russian',
		'Natural Language :: Slovak',
		'Natural Language :: Spanish',
		'Natural Language :: Swedish',
		'Natural Language :: Telugu',
		'Natural Language :: Thai',
		'Natural Language :: Turkish',
		'Natural Language :: Ukranian',
		'Natural Language :: Vietnamese '
      ]
     )

